// Process Image File
// Generated by CANopen Architect EDS 1.31 on Wed Jan 17 09:50:05 2007
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// Maximum number of receive PDOs
#define NR_OF_RPDOS       2

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#define NODE_ID           0x07

// device type
#define OD_DEVICE_TYPE    0x000F0191L

// Identity Object data [1018]
#define OD_VENDOR_ID      0x00455341L
#define OD_PRODUCT_CODE   0x00010002L
#define OD_REVISION       0x00000001L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 0

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// mapping entries for RPDO1 [1400]
// [6200,01] UNSIGNED8
#define P620001_DIGOUTPUT8_ 0x00000000
// [6200,02] UNSIGNED8
#define P620002_DIGOUTPUT8_ 0x00000001
// [6200,03] UNSIGNED8
#define P620003_DIGOUTPUT8_ 0x00000002
// [6200,04] UNSIGNED8
#define P620004_DIGOUTPUT8_ 0x00000003
// mapping entries for RPDO2 [1401]
// [6411,01] INTEGER16
#define P641101_ANALOGOUTPUT16_ 0x00000004
// [6411,02] INTEGER16
#define P641102_ANALOGOUTPUT16_ 0x00000006
// mapping entries for TPDO1 [1800]
// [6000,01] UNSIGNED8
#define P600001_DIGINPUT8_ 0x00000008
// [6000,02] UNSIGNED8
#define P600002_DIGINPUT8_ 0x00000009
// [6000,03] UNSIGNED8
#define P600003_DIGINPUT8_ 0x0000000A
// [6000,04] UNSIGNED8
#define P600004_DIGINPUT8_ 0x0000000B
// mapping entries for TPDO2 [1801]
// [6401,01] INTEGER16
#define P640101_ANALOGINPUT16_ 0x0000000C
// [6401,02] INTEGER16
#define P640102_ANALOGINPUT16_ 0x0000000E

// [1018,04] UNSIGNED32
#define P101804_SERIAL_NUMBER 0x00000010

// last byte used in process image
#define PIMGEND 0x00000013

// storage sizes for arrays in the process image
// storage size in bytes for entries in the array at [6200]
#define STORAGESIZEOF_6200_WRITE_STATE_8_OUTPUT_LINES 4
// storage size in bytes for entries in the array at [6411]
#define STORAGESIZEOF_6411_WRITE_ANALOG_OUTPUT_16_BIT 4
// storage size in bytes for entries in the array at [6000]
#define STORAGESIZEOF_6000_READ_STATE_8_INPUT_LINES 4
// storage size in bytes for entries in the array at [6401]
#define STORAGESIZEOF_6401_READ_ANALOG_INPUT_16_BIT 4
// storage size in bytes for entries in the array at [1018]
#define STORAGESIZEOF_1018_IDENTITY_OBJECT 4

// default values for process image
#define PIMGDEFAULTS { \
/*[6200,01]*/        0x00, \
/*[6200,02]*/        0x00, \
/*[6200,03]*/        0x00, \
/*[6200,04]*/        0x00, \
/*[6411,01]*/        0x00, 0x00, \
/*[6411,02]*/        0x00, 0x00, \
/*[6000,01]*/        0x00, \
/*[6000,02]*/        0x00, \
/*[6000,03]*/        0x00, \
/*[6000,04]*/        0x00, \
/*[6401,01]*/        0x00, 0x00, \
/*[6401,02]*/        0x00, 0x00, \
/*[1018,04]*/        0x98, 0xBA, 0xDC, 0xFE, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
//
// PIMGDEFAULTS

#endif
